### ISSUE TITLE
tsconfigs@4

### ISSUE THREAD

**Issue by mightyiam** [rasenplanscher/tsconfig.js#1]
Hi, @rasenplanscher. Thank you for publishing this open source.

I am the author of tsconfigs, a devDep of this project. I have recently released a breaking-change version 4. It's a re-write. I feel it's much better. I tried to make a PR for you to upgrade here, but it was a bit too complicated for the time I gave it.

Thank you for using tsconfigs. I apologize for the breaking change. I hope you like the new version.

**Comment by rasenplanscher** [comment]
@mightyiam Thanks for the heads-up! I had a look, and it does definitely looks cleaner. Updated my tests and dependencies 👍
